name: Coding Standards
'on':
  push: null
  pull_request: null
  workflow_dispatch: null
jobs:
  coding-standards:
    name: Coding Standards
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - '8.0'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Setup PHP ${{ matrix.php-version }}'
        uses: shivammathur/setup-php@v2
        with:
          php-version: '${{ matrix.php-version }}'
          tools: 'phpcs, cs2pr'
          coverage: none
      - name: Get composer cache directory
        id: composer-cache
        run: 'echo "::set-output name=dir::$(composer config cache-files-dir)"'
      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: '${{ steps.composer-cache.outputs.dir }}'
          key: '${{ runner.os }}-composer-${{ hashFiles(''**/composer.json'') }}'
          restore-keys: '${{ runner.os }}-composer-'
      - name: Install dependencies with Composer
        run: |
          composer install --no-interaction --no-progress --prefer-dist
          composer global require --dev doctrine/coding-standard ^8.1
      - name: Run PHP_CodeSniffer
        run: composer global exec -v -- phpcs --standard=./phpcs.xml src tests
